/*
 Copyright � 2011, Yellow Pages Group Co.  All rights reserved.
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 
 1)	Redistributions of source code must retain a complete copy of this notice, including the copyright notice, this list of conditions and the following disclaimer; and
 2)	Neither the name of the Yellow Pages Group Co., nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT OWNER AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>

#import "YPPhone.h"
#import "YPAddress.h"

typedef CLLocationCoordinate2D YPLocation;

/**
 @brief The YPListing class
 
 Represents an entire listing generated by the YellowAPI.
 */
@interface YPListing : NSObject {
@private
	NSString *identifier;
	NSString *name;
	NSString *enLogo;
	NSString *frLogo;
	NSString *merchantUrl;
	NSArray  *phones;
	YPAddress *address;
	YPLocation location;
}

/**
 @brief The unique identifier of this listing as generated by the YellowAPI
 */
@property (nonatomic, readwrite,   copy) NSString *identifier;

/**
 @brief The name of the merchant
 */
@property (nonatomic, readwrite,   copy) NSString *name;

/**
 @brief The URL of the english logo for this merchant
 */
@property (nonatomic, readwrite,   copy) NSString *enLogo;

/**
 @brief The URL of the french logo for this merchant
 */
@property (nonatomic, readwrite,   copy) NSString *frLogo;

/**
 @brief The permalink to the YellowPages merchant site
 */
@property (nonatomic, readwrite,   copy) NSString *merchantUrl;

/**
 @brief An array of all phone numbers associated with this merchant
 */
@property (nonatomic, readwrite, retain) NSArray  *phones;

/**
 @brief The YPAddress associated with this merchant
 */
@property (nonatomic, readwrite, retain) YPAddress *address;

/**
 @brief The YPLocation (CLLocation) associated with this merchant
 */
@property (nonatomic, readwrite, assign) YPLocation location;

/**
 @brief Initialize this listing using an NSDictionary
 */
- (id)initWithDictionary:(NSDictionary *)dict;

/**
 @brief Update this listing using an NSDictionary
 */
- (void)updateWithDictionary:(NSDictionary *)dict;

@end
